<?php use App\Core\Authorization; ?>
<div class="tuition-page">
<div class="page-heading"><div><p class="eyebrow">Finance</p><h1>Student tuition fees</h1><p>Configure fees by grade level, then record each student's payments.</p></div><div class="hero-actions"><?php if(Authorization::allows('tuition.record_payment')):?><a class="button primary" href="<?=e(url('/tuition/payment'))?>">Make a payment</a><?php endif;?><?php if(Authorization::allows('tuition.manage')):?><a class="button" href="<?=e(url('/tuition/create'))?>">Create grade assessment</a><?php endif;?></div></div>
<div class="grid three tuition-summary"><article class="stat-card"><span>Total assessed</span><strong><?=e($currency)?> <?=number_format((float)$summary['assessed'],2)?></strong><small>All active school fees</small></article><article class="stat-card"><span>Total collected</span><strong><?=e($currency)?> <?=number_format((float)$summary['collected'],2)?></strong><small>Recorded payments</small></article><article class="stat-card"><span>Outstanding balance</span><strong><?=e($currency)?> <?=number_format((float)$summary['outstanding'],2)?></strong><small>Open assessments only</small></article></div>
<section class="card table-card grade-fee-schedules"><div class="table-heading"><div><h2>Grade-level assessments</h2><small>Fee schedules available when recording student payments</small></div><span class="badge"><?=count($schedules)?> configured</span></div><table><thead><tr><th>Grade level</th><th>School year / term</th><th>Assessment</th><th>Tuition</th><th>Entrance</th><th>PACES</th><th>Closing</th><th>Shuttle</th><th>Total</th></tr></thead><tbody><?php foreach($schedules as $s):?><tr><td><strong><?=e($s['grade_level'])?></strong></td><td><?=e($s['school_year'])?><?= $s['term_name']?'<br><small>'.e($s['term_name']).'</small>':''?></td><td><?=e($s['description'])?></td><?php foreach(['tuition_fee_amount','entrance_fee_amount','paces_fee_amount','closing_fee_amount','shuttle_fee_amount'] as $key):?><td class="money"><?=number_format((float)$s[$key],2)?></td><?php endforeach;?><td class="money"><strong><?=e($currency)?> <?=number_format((float)$s['amount'],2)?></strong></td></tr><?php endforeach;?><?php if(!$schedules):?><tr><td colspan="9" class="empty">No grade-level assessments yet. Create one before accepting a payment.</td></tr><?php endif;?></tbody></table></section>
<div class="section-title"><div><p class="eyebrow">Student accounts</p><h2>Payment ledger</h2></div></div>
<form class="tuition-filter" method="get"><input name="q" value="<?=e($q)?>" placeholder="Student number, name, or assessment"><select name="school_year_id"><option value="">All school years</option><?php foreach($schoolYears as $y):?><option value="<?=$y['id']?>" <?=$year===(int)$y['id']?'selected':''?>><?=e($y['name'])?></option><?php endforeach;?></select><select name="status"><option value="">All statuses</option><?php foreach(['open','paid','waived','cancelled'] as $x):?><option value="<?=$x?>" <?=$status===$x?'selected':''?>><?=e(ucfirst($x))?></option><?php endforeach;?></select><button class="button">Filter</button></form>
<section class="card table-card tuition-ledger"><table><thead><tr><th>Student</th><th>Date</th><th>Tuition</th><th>Entrance fee</th><th>PACES</th><th>Closing fee</th><th>Shuttle</th><th>Payment</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody>
<?php foreach($assessments as $a):?><tr><td><strong><?=e($a['student_name'])?></strong><br><small><?=e($a['student_no'])?> · <?=e($a['description'])?></small></td><td><?=e($a['due_date']?:date('Y-m-d',strtotime($a['created_at'])))?><?php if($a['status']==='open'&&$a['due_date']&&$a['due_date']<date('Y-m-d')):?><br><span class="overdue-label">Overdue</span><?php endif;?></td>
<?php foreach(['tuition_fee_amount','entrance_fee_amount','paces_fee_amount','closing_fee_amount','shuttle_fee_amount'] as $key):?><td class="money"><?=number_format((float)$a[$key],2)?></td><?php endforeach;?><td class="money"><?=number_format((float)$a['paid_amount'],2)?></td><td class="money"><strong><?=e($currency)?> <?=number_format((float)$a['balance'],2)?></strong></td><td><span class="badge"><?=e($a['status'])?></span></td><td><a class="button small" href="<?=e(url('/tuition/'.$a['id']))?>">View</a></td></tr>
<?php endforeach;?><?php if(!$assessments):?><tr><td colspan="11" class="empty">No tuition assessments found.</td></tr><?php endif;?></tbody></table></section>
</div>
