<?php use App\Core\Csrf;$v=fn($key)=>$input[$key]??''; ?>
<div class="page-heading"><div><p class="eyebrow">Finance</p><h1>Make a tuition payment</h1><p>Select the student first, then record a payment against the assessment for their grade level.</p></div><a class="button" href="<?=e(url('/tuition'))?>">Cancel</a></div>
<?php if($errors):?><div class="alert danger"><?=e(implode(' ',$errors))?></div><?php endif;?>
<form method="post" action="<?=e(url('/tuition/payment'))?>" class="stack-form"><section class="card form-section"><?=Csrf::field()?><h2>Student and assessment</h2><div class="grid two">
<label>Student name or number<select required name="student_id"><option value="">Select student</option><?php foreach($students as $s):?><option value="<?=$s['id']?>" data-year="<?=$s['school_year_id']?>" data-grade="<?=$s['grade_level_id']?>" <?=(string)$v('student_id')===(string)$s['id']?'selected':''?>><?=e($s['last_name'].', '.$s['first_name'].' — '.$s['student_no'].' · '.$s['grade_level'].' · '.$s['school_year'])?></option><?php endforeach;?></select></label>
<label>Applicable grade assessment<select required name="fee_schedule_id"><option value="">Select student first</option><?php foreach($schedules as $s):?><option value="<?=$s['id']?>" data-year="<?=$s['school_year_id']?>" data-grade="<?=$s['grade_level_id']?>" data-total="<?=$s['amount']?>" <?=(string)$v('fee_schedule_id')===(string)$s['id']?'selected':''?>><?=e($s['grade_level'].' · '.$s['school_year'].($s['term_name']?' · '.$s['term_name']:'').' — '.$s['description'].' ('.$currency.' '.number_format((float)$s['amount'],2).')')?></option><?php endforeach;?></select><small id="assessment-help">Only assessments matching the student's current enrollment are shown.</small></label>
</div></section><section class="card form-section payment-entry"><h2>Payment details</h2><div class="grid two">
<label>Payment amount (<?=e($currency)?>)<input required type="number" min="0.01" step="0.01" name="amount" value="<?=e((string)$v('amount'))?>"></label><label>Payment for<select required name="payment_for"><?php foreach(['tuition'=>'Tuition','entrance_fee'=>'Entrance fee','paces'=>'PACES','closing_fee'=>'Closing fee','shuttle'=>'Shuttle','other'=>'Other'] as $key=>$label):?><option value="<?=$key?>" <?=$v('payment_for')===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select></label>
<label>Payment date<input required type="date" name="paid_on" value="<?=e((string)($v('paid_on')?:date('Y-m-d')))?>"></label><label>Receipt number<input name="receipt_no" value="<?=e((string)$v('receipt_no'))?>" placeholder="Leave blank to auto-generate"></label><label>Method<select name="payment_method"><?php foreach(['cash'=>'Cash','bank_transfer'=>'Bank transfer','card'=>'Card','cheque'=>'Cheque','other'=>'Other'] as $key=>$label):?><option value="<?=$key?>" <?=$v('payment_method')===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select></label>
</div><label>Remarks<input name="remarks" maxlength="500" value="<?=e((string)$v('remarks'))?>"></label></section><div class="sticky-actions"><button class="button primary">Record payment</button></div></form>
<script>
const student=document.querySelector('[name="student_id"]'),schedule=document.querySelector('[name="fee_schedule_id"]'),scheduleOptions=[...schedule.options].map(option=>option.cloneNode(true)),help=document.getElementById('assessment-help');
function filterSchedules(){const selected=student.selectedOptions[0],previous=schedule.value,year=selected?.dataset.year,grade=selected?.dataset.grade;const matches=scheduleOptions.filter(option=>!option.value||(option.dataset.year===year&&option.dataset.grade===grade)).map(option=>option.cloneNode(true));matches[0].textContent=student.value?(matches.length>1?'Select grade assessment':'No assessment configured for this grade'):'Select student first';schedule.replaceChildren(...matches);if([...schedule.options].some(option=>option.value===previous))schedule.value=previous;help.textContent=matches.length>1?'Only assessments matching the student\'s current enrollment are shown.':'Create a grade-level assessment before recording this payment.';}
student.addEventListener('change',filterSchedules);filterSchedules();
</script>
