<?php
declare(strict_types=1);
namespace App\Controllers\Admin;
use App\Core\Auth;use App\Core\Database;use App\Core\Env;use App\Core\View;use RuntimeException;
final class BackupController
{
    private string $directory;
    public function __construct(){$this->directory=APP_ROOT.'/storage/backups';if(!is_dir($this->directory))mkdir($this->directory,0775,true);}
    public function index():void{$backups=Database::connection()->query('SELECT b.*,u.display_name creator FROM backup_history b JOIN users u ON u.id=b.created_by ORDER BY b.created_at DESC')->fetchAll();View::render('admin/backups/index',compact('backups'));}
    public function create():void
    {$name='school-monitoring-'.date('Ymd-His').'.sql';$path=$this->directory.'/'.$name;try{$this->dump($path);$size=filesize($path)?:0;$checksum=hash_file('sha256',$path);Database::connection()->prepare('INSERT INTO backup_history(file_name,file_size,checksum_sha256,created_by) VALUES(?,?,?,?)')->execute([$name,$size,$checksum,Auth::user()['id']]);Auth::audit('backups.created','backup_history',(string)Database::connection()->lastInsertId(),null,['file_name'=>$name,'checksum'=>$checksum]);flash('success','Database backup created and verified.');}catch(\Throwable $e){if(is_file($path))unlink($path);flash('error','Backup failed: '.$e->getMessage());}Auth::redirect('/admin/backups');}
    public function download(string $id):void{$backup=$this->find((int)$id);if(!$backup)return;$path=$this->safePath($backup['file_name']);if(!$path||!is_file($path)){http_response_code(404);View::render('errors/message',['title'=>'Backup missing','message'=>'The backup file is no longer available.']);return;}header('Content-Type: application/sql');header('Content-Disposition: attachment; filename="'.basename($backup['file_name']).'"');header('Content-Length: '.filesize($path));readfile($path);}
    public function restore(string $id):void
    {if(($_POST['confirm_text']??'')!=='RESTORE'){flash('error','Type RESTORE exactly to confirm.');Auth::redirect('/admin/backups');}$stmt=Database::connection()->prepare('SELECT password_hash FROM users WHERE id=?');$stmt->execute([Auth::user()['id']]);if(!password_verify((string)($_POST['current_password']??''),(string)$stmt->fetchColumn())){flash('error','Current administrator password is incorrect.');Auth::redirect('/admin/backups');}$backup=$this->find((int)$id);if(!$backup)return;$path=$this->safePath($backup['file_name']);if(!$path||!is_file($path)||!hash_equals((string)$backup['checksum_sha256'],hash_file('sha256',$path))){flash('error','Backup file is missing or its checksum does not match.');Auth::redirect('/admin/backups');}try{$this->import($path);Database::reset();Database::connection()->prepare('UPDATE backup_history SET status="restored",restored_at=NOW() WHERE id=?')->execute([(int)$id]);Auth::audit('backups.restored','backup_history',$id,null,['file_name'=>$backup['file_name']]);flash('success','Database restored. Review the application data before continuing.');}catch(\Throwable $e){Database::reset();flash('error','Restore failed: '.$e->getMessage());}Auth::redirect('/admin/backups');}
    private function dump(string $path):void{$binary='C:/xampp/mysql/bin/mysqldump.exe';if(!is_file($binary))throw new RuntimeException('mysqldump.exe was not found in XAMPP.');$credentials=$this->credentialsFile();try{$args=[$binary,'--defaults-extra-file='.$credentials,'--single-transaction','--routines','--triggers'];$args[]=Env::get('DB_NAME','school_monitoring');$this->process($args,[0=>['pipe','r'],1=>['file',$path,'wb'],2=>['pipe','w']]);}finally{if(is_file($credentials))unlink($credentials);}if(!is_file($path)||filesize($path)===0)throw new RuntimeException('The backup output was empty.');}
    private function import(string $path):void{$binary='C:/xampp/mysql/bin/mysql.exe';if(!is_file($binary))throw new RuntimeException('mysql.exe was not found in XAMPP.');$credentials=$this->credentialsFile();try{$args=[$binary,'--defaults-extra-file='.$credentials,Env::get('DB_NAME','school_monitoring')];$this->process($args,[0=>['file',$path,'rb'],1=>['pipe','w'],2=>['pipe','w']]);}finally{if(is_file($credentials))unlink($credentials);}}
    private function credentialsFile():string{$path=tempnam(sys_get_temp_dir(),'school-db-');if($path===false)throw new RuntimeException('Could not create a temporary database credentials file.');$escape=static fn(string $value):string=>str_replace(['\\','"'],['\\\\','\\"'],$value);$contents="[client]\n".'host="'.$escape(Env::get('DB_HOST','127.0.0.1'))."\"\n".'port="'.$escape(Env::get('DB_PORT','3306'))."\"\n".'user="'.$escape(Env::get('DB_USER','root'))."\"\n".'password="'.$escape(Env::get('DB_PASS',''))."\"\n"."default-character-set=utf8mb4\n";if(file_put_contents($path,$contents,LOCK_EX)===false){unlink($path);throw new RuntimeException('Could not write the temporary database credentials file.');}chmod($path,0600);return$path;}
    private function process(array $command,array $descriptors):void{$pipes=[];$process=proc_open($command,$descriptors,$pipes,APP_ROOT);if(!is_resource($process))throw new RuntimeException('Could not start the database utility.');if(isset($pipes[0])&&is_resource($pipes[0]))fclose($pipes[0]);$error='';if(isset($pipes[2])&&is_resource($pipes[2])){$error=stream_get_contents($pipes[2]);fclose($pipes[2]);}if(isset($pipes[1])&&is_resource($pipes[1]))fclose($pipes[1]);$code=proc_close($process);if($code!==0)throw new RuntimeException(trim($error)?:'Database utility exited with code '.$code.'.');}
    private function safePath(string $file):?string{$name=basename($file);if($name!==$file||!preg_match('/^[A-Za-z0-9_.-]+\.sql$/',$name))return null;return $this->directory.'/'.$name;}
    private function find(int $id):?array{$s=Database::connection()->prepare('SELECT * FROM backup_history WHERE id=?');$s->execute([$id]);$b=$s->fetch();if(!$b){http_response_code(404);View::render('errors/message',['title'=>'Backup not found','message'=>'The selected backup record does not exist.']);return null;}return$b;}
}
