<?php use App\Core\Csrf; $v=fn($k)=>$input[$k]??$student[$k]??''; $editing=(bool)$student; $selfEditing=$selfEditing??false; ?>
<div class="student-form-page">
<div class="page-heading"><div><p class="eyebrow">Student profile</p><h1><?=$selfEditing?'Edit my profile':($editing?'Edit student':'Add student')?></h1></div><a class="button" href="<?=e(url($selfEditing?'/students/'.$student['id']:'/students'))?>">Cancel</a></div>
<?php if($errors):?><div class="alert danger"><?=e($errors['form']??'Please correct the highlighted information.')?></div><?php endif;?>
<form class="stack-form" method="post" action="<?=e($editing?url('/students/'.$student['id']):url('/students'))?>"><?=Csrf::field()?>
<?php if(!$editing):?><div class="alert success">The student number will become the login username. A temporary password will be generated after saving.</div><?php endif;?>
<section class="card form-section"><h2>Identity</h2><?php if($selfEditing):?><p><small>Student number: <?=e($v('student_no'))?>. Enrollment and status are maintained by school staff.</small></p><?php endif;?><div class="grid three"><?php if(!$selfEditing):?><label>Student number<input required name="student_no" value="<?=e($v('student_no'))?>"></label><?php endif;?><label>First name<input required name="first_name" value="<?=e($v('first_name'))?>"></label><label>Middle name<input name="middle_name" value="<?=e($v('middle_name'))?>"></label><label>Last name<input required name="last_name" value="<?=e($v('last_name'))?>"></label><label>Suffix<input name="suffix" value="<?=e($v('suffix'))?>"></label><label>Sex<select name="sex"><option value="">Not specified</option><?php foreach(['male','female','other','prefer_not_to_say'] as $x):?><option value="<?=$x?>" <?=$v('sex')===$x?'selected':''?>><?=e(ucwords(str_replace('_',' ',$x)))?></option><?php endforeach;?></select></label><label>Birth date<input type="date" name="birth_date" value="<?=e($v('birth_date'))?>"></label><?php if(!$selfEditing):?><label>Admission date<input type="date" name="admission_date" value="<?=e($v('admission_date'))?>"></label><label>Status<select name="student_status"><?php foreach(['active','inactive','graduated','transferred','withdrawn'] as $x):?><option value="<?=$x?>" <?=$v('student_status')===$x?'selected':''?>><?=e(ucfirst($x))?></option><?php endforeach;?></select></label><?php endif;?></div></section>
<section class="card form-section"><h2>Contact</h2><div class="grid two"><label>Email<input type="email" name="email" value="<?=e($v('email'))?>"></label><label>Phone<input type="text" inputmode="numeric" autocomplete="tel" pattern="[0-9]{11}" minlength="11" maxlength="11" title="Enter exactly 11 digits." placeholder="09XXXXXXXXX" oninput="this.value=this.value.replace(/[^0-9]/g,'').slice(0,11)" name="phone" value="<?=e($v('phone'))?>"></label></div><label>Address<textarea name="address" rows="3"><?=e($v('address'))?></textarea></label></section>
<?php if(!$selfEditing):?><section class="card form-section"><h2>Current enrollment</h2><p><small>Leave both blank if enrollment will be added later.</small></p><div class="grid two"><label>School year<select name="school_year_id"><option value="">Not selected</option><?php foreach($schoolYears as $y):?><option value="<?=$y['id']?>"><?=e($y['name'])?></option><?php endforeach;?></select></label><label>Section<select name="section_id"><option value="">Not selected</option><?php foreach($sections as $s):?><option value="<?=$s['id']?>" data-year="<?=$s['school_year_id']?>"><?=e($s['school_year'].' — '.$s['grade_level'].' '.$s['name'])?></option><?php endforeach;?></select></label></div></section><?php endif;?>
<div class="sticky-actions"><button class="button primary">Save student</button></div></form>
</div>
