<?php use App\Core\Csrf; $v=fn($k)=>$input[$k]??$teacher[$k]??'';$editing=(bool)$teacher;$selfEditing=$selfEditing??false; ?>
<div class="teacher-form-page">
<div class="page-heading"><div><p class="eyebrow">Teacher profile</p><h1><?=$selfEditing?'Edit my profile':($editing?'Edit teacher':'Add teacher')?></h1></div><a class="button" href="<?=e(url($selfEditing?'/teachers/'.$teacher['id']:'/teachers'))?>">Cancel</a></div><?php if($errors):?><div class="alert danger"><?=e($errors['form']??'Review the form and correct the information that could not be saved.')?></div><?php endif;?><form class="stack-form" method="post" action="<?=e($editing?url('/teachers/'.$teacher['id']):url('/teachers'))?>"><?=Csrf::field()?>
<?php if(!$editing):?><div class="alert success">The employee number will become the login username. A temporary password will be generated after saving.</div><?php endif;?>
<section class="card form-section"><h2>Employment</h2><?php if($selfEditing):?><p><small>Employee number, department, hire date, employment status, and assignments are maintained by school administrators.</small></p><dl><dt>Employee number</dt><dd><?=e($v('employee_no'))?></dd><dt>Department</dt><dd><?=e($teacher['department']?:'—')?></dd><dt>Hire date</dt><dd><?=e($v('hire_date')?:'—')?></dd><dt>Status</dt><dd><?=e(str_replace('_',' ',$v('employment_status')))?></dd></dl><?php else:?><div class="grid three"><label>Employee number<input required name="employee_no" value="<?=e($v('employee_no'))?>"></label><label>Department<select name="department_id"><option value="">Not assigned</option><?php foreach($departments as $d):?><option value="<?=$d['id']?>" <?=((string)$v('department_id')===(string)$d['id'])?'selected':''?>><?=e($d['name'])?></option><?php endforeach;?></select></label><label>Hire date<input type="date" name="hire_date" value="<?=e($v('hire_date'))?>"></label><label>Status<select name="employment_status"><?php foreach(['active','on_leave','inactive','separated'] as $x):?><option value="<?=$x?>" <?=$v('employment_status')===$x?'selected':''?>><?=e(ucwords(str_replace('_',' ',$x)))?></option><?php endforeach;?></select></label></div><?php endif;?></section>
<section class="card form-section"><h2>Personal information</h2><div class="grid three"><label>First name<input required name="first_name" value="<?=e($v('first_name'))?>"></label><label>Middle name<input name="middle_name" value="<?=e($v('middle_name'))?>"></label><label>Last name<input required name="last_name" value="<?=e($v('last_name'))?>"></label><label>Suffix<input name="suffix" value="<?=e($v('suffix'))?>"></label><label>Sex<select name="sex"><option value="">Not specified</option><?php foreach(['male','female','other','prefer_not_to_say'] as $x):?><option value="<?=$x?>" <?=$v('sex')===$x?'selected':''?>><?=e(ucwords(str_replace('_',' ',$x)))?></option><?php endforeach;?></select></label><label>Birth date<input type="date" name="birth_date" value="<?=e($v('birth_date'))?>"></label></div></section>
<section class="card form-section"><h2>Government identification <small>(optional)</small></h2><div class="grid three"><label>SSS No.<input type="text" maxlength="30" name="sss_no" value="<?=e($v('sss_no'))?>" placeholder="00-0000000-0"></label><label>Pag-IBIG No.<input type="text" maxlength="30" name="pagibig_no" value="<?=e($v('pagibig_no'))?>" placeholder="0000-0000-0000"></label><label>PhilHealth No.<input type="text" maxlength="30" name="philhealth_no" value="<?=e($v('philhealth_no'))?>" placeholder="00-000000000-0"></label></div></section>
<section class="card form-section"><h2>Contact</h2><div class="grid two"><label>Email<input type="email" name="email" value="<?=e($v('email'))?>"></label><label>Phone<input type="text" inputmode="numeric" autocomplete="tel" pattern="[0-9]{11}" minlength="11" maxlength="11" title="Enter exactly 11 digits." placeholder="09XXXXXXXXX" oninput="this.value=this.value.replace(/[^0-9]/g,'').slice(0,11)" name="phone" value="<?=e($v('phone'))?>"></label></div><label>Address<textarea name="address" rows="3"><?=e($v('address'))?></textarea></label></section><div class="sticky-actions"><button class="button primary"><?=$selfEditing?'Save my profile':'Save teacher'?></button></div></form>
</div>
