<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Core\Auth;use App\Core\Authorization;use App\Core\Database;use App\Core\View;use DateTimeImmutable;use Throwable;
final class EventController
{
    private const STATUSES=['draft','published','ongoing','completed','cancelled'];
    private const VISIBILITIES=['all','students','teachers','staff','invited'];
    private const ATTENDANCE=['present','absent','late','excused','unrecorded'];
    public function index():void
    {$q=trim($_GET['q']??'');$status=trim($_GET['status']??'');$sql='SELECT e.*,u.display_name organizer,(SELECT COUNT(*) FROM event_participants ep WHERE ep.event_id=e.id AND ep.registration_status IN ("invited","registered")) participant_count FROM events e JOIN users u ON u.id=e.organizer_user_id WHERE 1=1';$args=[];if($q!==''){$sql.=' AND (e.title LIKE ? OR e.venue LIKE ?)';$like='%'.$q.'%';$args=[$like,$like];}if(in_array($status,self::STATUSES,true)){$sql.=' AND e.status=?';$args[]=$status;}$sql.=' ORDER BY e.starts_at DESC LIMIT 200';$stmt=Database::connection()->prepare($sql);$stmt->execute($args);View::render('events/index',['events'=>$stmt->fetchAll(),'q'=>$q,'status'=>$status]);}
    public function create():void{View::render('events/form',['event'=>null,'errors'=>[],'input'=>[]]);}
    public function edit(string $id):void{$event=$this->find((int)$id);if($event)View::render('events/form',['event'=>$event,'errors'=>[],'input'=>[]]);}
    public function show(string $id):void
    {$event=$this->find((int)$id);if(!$event)return;$pdo=Database::connection();$stmt=$pdo->prepare('SELECT ep.*,COALESCE(CONCAT(s.last_name,", ",s.first_name),CONCAT(t.last_name,", ",t.first_name),u.display_name) participant_name,COALESCE(s.student_no,t.employee_no,u.username) reference_no,ea.status attendance_status,ea.checked_in_at,ea.checked_out_at,ea.remarks attendance_remarks FROM event_participants ep LEFT JOIN students s ON s.id=ep.student_id LEFT JOIN teachers t ON t.id=ep.teacher_id LEFT JOIN users u ON u.id=ep.user_id LEFT JOIN event_attendance ea ON ea.event_participant_id=ep.id WHERE ep.event_id=? ORDER BY ep.participant_type,participant_name');$stmt->execute([$id]);$participants=$stmt->fetchAll();$students=$pdo->query('SELECT id,student_no,first_name,last_name FROM students WHERE student_status="active" ORDER BY last_name,first_name')->fetchAll();$teachers=$pdo->query('SELECT id,employee_no,first_name,last_name FROM teachers WHERE employment_status="active" ORDER BY last_name,first_name')->fetchAll();View::render('events/show',compact('event','participants','students','teachers')+['attendanceStatuses'=>self::ATTENDANCE,'canManage'=>Authorization::allows('events.manage_participants')]);}
    public function store():void{$this->save();}public function update(string $id):void{$this->save((int)$id);}
    private function save(?int $id=null):void
    {$creating=$id===null;$in=$this->input();$errors=[];foreach(['title'=>'Title','starts_at'=>'Start date and time','ends_at'=>'End date and time'] as $k=>$label)if($in[$k]==='')$errors[$k]=$label.' is required.';if(!in_array($in['status'],self::STATUSES,true))$errors['status']='Invalid status.';if(!in_array($in['visibility'],self::VISIBILITIES,true))$errors['visibility']='Invalid visibility.';$start=$this->dateTime($in['starts_at']);$end=$this->dateTime($in['ends_at']);if(!$start||!$end||$end<$start)$errors['dates']='Enter a valid schedule where the end follows the start.';if($errors){View::render('events/form',['event'=>$id?$this->raw($id):null,'errors'=>$errors,'input'=>$in]);return;}$pdo=Database::connection();$values=[$in['title'],$in['description']?:null,$in['venue']?:null,$start->format('Y-m-d H:i:s'),$end->format('Y-m-d H:i:s'),$in['visibility'],$in['status'],$in['capacity']!==''?(int)$in['capacity']:null];try{if($id){$values[]=$id;$pdo->prepare('UPDATE events SET title=?,description=?,venue=?,starts_at=?,ends_at=?,visibility=?,status=?,capacity=? WHERE id=?')->execute($values);}else{$pdo->prepare('INSERT INTO events(title,description,venue,starts_at,ends_at,organizer_user_id,visibility,status,capacity) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$values[0],$values[1],$values[2],$values[3],$values[4],Auth::user()['id'],$values[5],$values[6],$values[7]]);$id=(int)$pdo->lastInsertId();}Auth::audit($creating?'events.created':'events.updated','events',(string)$id,null,$in);flash('success','Event saved.');Auth::redirect('/events/'.$id);}catch(\PDOException $e){$errors['form']='The event could not be saved.';View::render('events/form',['event'=>$id?$this->raw($id):null,'errors'=>$errors,'input'=>$in]);}}
    public function addParticipant(string $id):void
    {$event=$this->find((int)$id);if(!$event)return;$pdo=Database::connection();if($event['capacity']!==null){$count=$pdo->prepare('SELECT COUNT(*) FROM event_participants WHERE event_id=? AND registration_status IN ("invited","registered")');$count->execute([(int)$id]);if((int)$count->fetchColumn()>=(int)$event['capacity']){flash('error','This event has reached its participant capacity.');Auth::redirect('/events/'.$id);}}$type=$_POST['participant_type']??'';$profileId=(int)($_POST['profile_id']??0);if(!in_array($type,['student','teacher'],true)||!$profileId){flash('error','Choose a valid student or teacher.');Auth::redirect('/events/'.$id);}$column=$type.'_id';$table=$type==='student'?'students':'teachers';$check=$pdo->prepare("SELECT id FROM {$table} WHERE id=?");$check->execute([$profileId]);if(!$check->fetch()){flash('error','The selected participant does not exist.');Auth::redirect('/events/'.$id);}try{$stmt=$pdo->prepare("INSERT INTO event_participants(event_id,participant_type,{$column},registration_status,registered_at) VALUES(?,?,?,'registered',NOW())");$stmt->execute([(int)$id,$type,$profileId]);Auth::audit('events.participant_added','events',$id,null,['type'=>$type,'profile_id'=>$profileId]);flash('success','Participant added.');}catch(\PDOException $e){flash('error','That participant is already registered for this event.');}Auth::redirect('/events/'.$id);}
    public function recordAttendance(string $id):void
    {$event=$this->find((int)$id);if(!$event)return;$pdo=Database::connection();$allowed=$pdo->prepare('SELECT id FROM event_participants WHERE id=? AND event_id=?');$save=$pdo->prepare('INSERT INTO event_attendance(event_participant_id,status,checked_in_at,checked_out_at,remarks,recorded_by) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),checked_in_at=VALUES(checked_in_at),checked_out_at=VALUES(checked_out_at),remarks=VALUES(remarks),recorded_by=VALUES(recorded_by),updated_at=NOW()');$pdo->beginTransaction();try{foreach($_POST['attendance']??[] as $participantId=>$row){$participantId=(int)$participantId;$status=(string)($row['status']??'unrecorded');if(!in_array($status,self::ATTENDANCE,true))continue;$allowed->execute([$participantId,(int)$id]);if(!$allowed->fetch())continue;$in=$this->dateTime($row['checked_in_at']??'');$out=$this->dateTime($row['checked_out_at']??'');$save->execute([$participantId,$status,$in?$in->format('Y-m-d H:i:s'):null,$out?$out->format('Y-m-d H:i:s'):null,substr(trim($row['remarks']??''),0,500)?:null,Auth::user()['id']]);}$pdo->commit();Auth::audit('events.attendance_recorded','events',$id);flash('success','Event attendance saved.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error','Event attendance could not be saved.');}Auth::redirect('/events/'.$id);}
    private function input():array{return ['title'=>trim($_POST['title']??''),'description'=>trim($_POST['description']??''),'venue'=>trim($_POST['venue']??''),'starts_at'=>trim($_POST['starts_at']??''),'ends_at'=>trim($_POST['ends_at']??''),'visibility'=>trim($_POST['visibility']??'all'),'status'=>trim($_POST['status']??'draft'),'capacity'=>trim($_POST['capacity']??'')];}
    private function dateTime(string $value):?DateTimeImmutable{if($value==='')return null;try{return new DateTimeImmutable($value);}catch(Throwable $e){return null;}}
    private function raw(int $id):?array{$s=Database::connection()->prepare('SELECT e.*,u.display_name organizer FROM events e JOIN users u ON u.id=e.organizer_user_id WHERE e.id=?');$s->execute([$id]);return $s->fetch()?:null;}
    private function find(int $id):?array{$event=$this->raw($id);if(!$event){http_response_code(404);View::render('errors/message',['title'=>'Event not found','message'=>'The requested event does not exist.']);return null;}return $event;}
}
