<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Core\Authorization;use App\Core\Database;use App\Core\View;use DateTimeImmutable;
final class ReportController
{
    private const TYPES=['students','teachers','student-attendance','teacher-attendance','events','tuition','insurance','inventory','inventory-issues'];
    private const LABELS=['students'=>'Student directory','teachers'=>'Teacher directory','student-attendance'=>'Student attendance','teacher-attendance'=>'Teacher attendance','events'=>'Event summary','tuition'=>'Tuition fee balances','insurance'=>'Insurance coverage and expiry','inventory'=>'Uniform and ID stock','inventory-issues'=>'Uniform and ID assignments'];
    public function index():void{$type=$this->type();if(!$this->requireType($type))return;$from=$this->date($_GET['from']??date('Y-m-01'));$to=$this->date($_GET['to']??date('Y-m-d'));[$columns,$rows]=$this->data($type,$from,$to);$reportTypes=array_intersect_key(self::LABELS,array_flip(array_filter(self::TYPES,fn($candidate)=>$this->canAccessType($candidate))));View::render('reports/index',compact('type','from','to','columns','rows','reportTypes'));}
    public function export():void{$type=$this->type();if(!$this->requireType($type))return;$from=$this->date($_GET['from']??date('Y-m-01'));$to=$this->date($_GET['to']??date('Y-m-d'));[$columns,$rows]=$this->data($type,$from,$to);header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$type.'-'.$from.'-to-'.$to.'.csv"');$out=fopen('php://output','wb');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,array_values($columns));foreach($rows as $row){$line=[];foreach(array_keys($columns) as $key)$line[]=$this->csvValue((string)($row[$key]??''));fputcsv($out,$line);}fclose($out);}
    private function data(string $type,string $from,string $to):array
    {
        $pdo=Database::connection();
        $toExclusive=(new DateTimeImmutable($to))->modify('+1 day')->format('Y-m-d');
        switch($type){
            case'teachers':$columns=['employee_no'=>'Employee Number','name'=>'Teacher','sss_no'=>'SSS No.','pagibig_no'=>'Pag-IBIG No.','philhealth_no'=>'PhilHealth No.','department'=>'Department','email'=>'Email','phone'=>'Phone','employment_status'=>'Status'];$rows=$pdo->query('SELECT t.employee_no,CONCAT(t.last_name,", ",t.first_name) name,COALESCE(t.sss_no,"") sss_no,COALESCE(t.pagibig_no,"") pagibig_no,COALESCE(t.philhealth_no,"") philhealth_no,COALESCE(d.name,"") department,COALESCE(t.email,"") email,COALESCE(t.phone,"") phone,t.employment_status FROM teachers t LEFT JOIN departments d ON d.id=t.department_id ORDER BY t.last_name,t.first_name')->fetchAll();break;
            case'student-attendance':$columns=['attendance_date'=>'Date','student_no'=>'Student Number','name'=>'Student','class_name'=>'Class','status'=>'Status','arrival_time'=>'Arrival','remarks'=>'Remarks'];$s=$pdo->prepare('SELECT ats.attendance_date,st.student_no,CONCAT(st.last_name,", ",st.first_name) name,CONCAT(g.name," ",sec.name) class_name,sa.status,COALESCE(sa.arrival_time,"") arrival_time,COALESCE(sa.remarks,"") remarks FROM student_attendance sa JOIN attendance_sessions ats ON ats.id=sa.attendance_session_id JOIN students st ON st.id=sa.student_id JOIN sections sec ON sec.id=ats.section_id JOIN grade_levels g ON g.id=sec.grade_level_id WHERE ats.attendance_date BETWEEN ? AND ? ORDER BY ats.attendance_date,st.last_name');$s->execute([$from,$to]);$rows=$s->fetchAll();break;
            case'teacher-attendance':$columns=['attendance_date'=>'Date','employee_no'=>'Employee Number','name'=>'Teacher','status'=>'Status','time_in'=>'Time In','time_out'=>'Time Out','remarks'=>'Remarks'];$s=$pdo->prepare('SELECT ta.attendance_date,t.employee_no,CONCAT(t.last_name,", ",t.first_name) name,ta.status,COALESCE(ta.time_in,"") time_in,COALESCE(ta.time_out,"") time_out,COALESCE(ta.remarks,"") remarks FROM teacher_attendance ta JOIN teachers t ON t.id=ta.teacher_id WHERE ta.attendance_date BETWEEN ? AND ? ORDER BY ta.attendance_date,t.last_name');$s->execute([$from,$to]);$rows=$s->fetchAll();break;
            case'events':$columns=['title'=>'Event','starts_at'=>'Starts','ends_at'=>'Ends','venue'=>'Venue','status'=>'Status','participant_count'=>'Participants','present_count'=>'Present'];$s=$pdo->prepare('SELECT e.title,e.starts_at,e.ends_at,COALESCE(e.venue,"") venue,e.status,COUNT(DISTINCT ep.id) participant_count,SUM(CASE WHEN ea.status IN ("present","late") THEN 1 ELSE 0 END) present_count FROM events e LEFT JOIN event_participants ep ON ep.event_id=e.id LEFT JOIN event_attendance ea ON ea.event_participant_id=ep.id WHERE e.starts_at >= ? AND e.starts_at < ? GROUP BY e.id ORDER BY e.starts_at');$s->execute([$from,$toExclusive]);$rows=$s->fetchAll();break;
            case'tuition':$columns=['student_no'=>'Student Number','name'=>'Student','school_year'=>'School Year','description'=>'Assessment','due_date'=>'Date','tuition_fee_amount'=>'Tuition','entrance_fee_amount'=>'Entrance Fee','paces_fee_amount'=>'PACES','closing_fee_amount'=>'Closing Fee','shuttle_fee_amount'=>'Shuttle','amount'=>'Total Assessment','paid_amount'=>'Payment','balance'=>'Balance','status'=>'Status'];$s=$pdo->prepare('SELECT st.student_no,CONCAT(st.last_name,", ",st.first_name) name,sy.name school_year,a.description,COALESCE(a.due_date,DATE(a.created_at)) due_date,a.tuition_fee_amount,a.entrance_fee_amount,a.paces_fee_amount,a.closing_fee_amount,a.shuttle_fee_amount,a.amount,COALESCE(SUM(p.amount),0) paid_amount,(a.amount-COALESCE(SUM(p.amount),0)) balance,a.status FROM tuition_assessments a JOIN students st ON st.id=a.student_id JOIN school_years sy ON sy.id=a.school_year_id LEFT JOIN tuition_payments p ON p.tuition_assessment_id=a.id WHERE a.created_at >= ? AND a.created_at < ? GROUP BY a.id ORDER BY st.last_name,a.created_at');$s->execute([$from,$toExclusive]);$rows=$s->fetchAll();break;
            case'insurance':$columns=['holder_type'=>'Holder Type','reference_no'=>'Reference Number','holder_name'=>'Policy Holder','provider'=>'Provider','policy_no'=>'Policy Number','plan_name'=>'Plan','coverage_start'=>'Coverage Start','coverage_end'=>'Coverage End','premium_amount'=>'Premium','coverage_amount'=>'Coverage Amount','status'=>'Status','claim_count'=>'Claims'];$s=$pdo->prepare('SELECT p.holder_type,COALESCE(st.student_no,t.employee_no,e.employee_no) reference_no,COALESCE(CONCAT(st.last_name,", ",st.first_name),CONCAT(t.last_name,", ",t.first_name),CONCAT(e.last_name,", ",e.first_name)) holder_name,p.provider,p.policy_no,COALESCE(p.plan_name,"") plan_name,p.coverage_start,p.coverage_end,COALESCE(p.premium_amount,"") premium_amount,COALESCE(p.coverage_amount,"") coverage_amount,p.status,(SELECT COUNT(*) FROM insurance_claims c WHERE c.insurance_policy_id=p.id) claim_count FROM insurance_policies p LEFT JOIN students st ON st.id=p.student_id LEFT JOIN teachers t ON t.id=p.teacher_id LEFT JOIN employees e ON e.id=p.employee_id WHERE p.coverage_end BETWEEN ? AND ? ORDER BY p.coverage_end,holder_name');$s->execute([$from,$to]);$rows=$s->fetchAll();break;
            case'inventory':$columns=['sku'=>'SKU','item_type'=>'Type','name'=>'Item','variant'=>'Variant / Size','quantity_on_hand'=>'Available','issued_quantity'=>'Outstanding Issued','reorder_level'=>'Reorder Level','unit_cost'=>'Unit Cost','status'=>'Status'];$rows=$pdo->query('SELECT i.sku,CASE i.item_type WHEN "id_card" THEN "ID card" WHEN "uniform" THEN "Uniform" ELSE "Other item" END item_type,i.name,COALESCE(i.variant,"") variant,i.quantity_on_hand,(SELECT COALESCE(SUM(x.quantity-x.returned_quantity),0) FROM inventory_issues x WHERE x.inventory_item_id=i.id AND x.status<>"returned") issued_quantity,i.reorder_level,COALESCE(i.unit_cost,"") unit_cost,IF(i.is_active,"Active","Inactive") status FROM inventory_items i ORDER BY i.item_type,i.name,i.variant')->fetchAll();break;
            case'inventory-issues':$columns=['issued_on'=>'Issue Date','recipient_type'=>'Recipient Type','reference_no'=>'Reference Number','recipient_name'=>'Recipient','sku'=>'SKU','item_name'=>'Item','variant'=>'Variant / Size','quantity'=>'Issued','returned_quantity'=>'Returned','outstanding'=>'Outstanding','status'=>'Status'];$s=$pdo->prepare('SELECT x.issued_on,x.recipient_type,COALESCE(st.student_no,t.employee_no,e.employee_no) reference_no,COALESCE(CONCAT(st.last_name,", ",st.first_name),CONCAT(t.last_name,", ",t.first_name),CONCAT(e.last_name,", ",e.first_name)) recipient_name,i.sku,i.name item_name,COALESCE(i.variant,"") variant,x.quantity,x.returned_quantity,(x.quantity-x.returned_quantity) outstanding,x.status FROM inventory_issues x JOIN inventory_items i ON i.id=x.inventory_item_id LEFT JOIN students st ON st.id=x.student_id LEFT JOIN teachers t ON t.id=x.teacher_id LEFT JOIN employees e ON e.id=x.employee_id WHERE x.issued_on BETWEEN ? AND ? ORDER BY x.issued_on DESC,x.id DESC');$s->execute([$from,$to]);$rows=$s->fetchAll();break;
            default:$columns=['student_no'=>'Student Number','name'=>'Student','class_name'=>'Current Class','email'=>'Email','phone'=>'Phone','student_status'=>'Status'];$rows=$pdo->query('SELECT st.student_no,CONCAT(st.last_name,", ",st.first_name) name,COALESCE(CONCAT(g.name," ",s.name),"") class_name,COALESCE(st.email,"") email,COALESCE(st.phone,"") phone,st.student_status FROM students st LEFT JOIN enrollments e ON e.student_id=st.id AND e.status="enrolled" LEFT JOIN sections s ON s.id=e.section_id LEFT JOIN grade_levels g ON g.id=s.grade_level_id ORDER BY st.last_name,st.first_name')->fetchAll();
        }
        return[$columns,$rows];
    }
    private function type():string{$type=$_GET['type']??'';return in_array($type,self::TYPES,true)?$type:'students';}
    private function canAccessType(string $type):bool{return match($type){'students'=>Authorization::allows('students.view'),'teachers'=>Authorization::allows('teachers.view'),'student-attendance','teacher-attendance'=>Authorization::allows('attendance.view'),'events'=>Authorization::allows('events.view'),'tuition'=>Authorization::allows('tuition.view'),'insurance'=>Authorization::allows('insurance.view'),'inventory','inventory-issues'=>Authorization::allows('inventory.view'),default=>false};}
    private function requireType(string $type):bool{if($this->canAccessType($type))return true;http_response_code(403);View::render('errors/message',['title'=>'Access denied','message'=>'You do not have permission to view this report.']);return false;}
    private function date(string $value):string{$d=DateTimeImmutable::createFromFormat('Y-m-d',$value);return$d&&$d->format('Y-m-d')===$value?$value:date('Y-m-d');}
    private function csvValue(string $value):string{return preg_match('/^[=+\-@]/',$value)?"'".$value:$value;}
}
