<?php
declare(strict_types=1);
namespace App\Controllers;

use App\Core\Auth;
use App\Core\Database;
use App\Core\View;
use DateTimeImmutable;
use PDO;
use Throwable;

final class TuitionController
{
    private const FEE_KEYS=['tuition_fee_amount','entrance_fee_amount','paces_fee_amount','closing_fee_amount','shuttle_fee_amount'];

    public function index():void
    {
        $pdo=Database::connection();$q=trim($_GET['q']??'');$status=trim($_GET['status']??'');$year=(int)($_GET['school_year_id']??0);
        $sql='SELECT a.*,s.student_no,CONCAT(s.last_name,", ",s.first_name) student_name,sy.name school_year,COALESCE(SUM(p.amount),0) paid_amount,(a.amount-COALESCE(SUM(p.amount),0)) balance FROM tuition_assessments a JOIN students s ON s.id=a.student_id JOIN school_years sy ON sy.id=a.school_year_id LEFT JOIN tuition_payments p ON p.tuition_assessment_id=a.id WHERE 1=1';$args=[];
        if($q!==''){$sql.=' AND (s.student_no LIKE ? OR s.first_name LIKE ? OR s.last_name LIKE ? OR a.description LIKE ?)';$like='%'.$q.'%';$args=[$like,$like,$like,$like];}
        if(in_array($status,['open','paid','waived','cancelled'],true)){$sql.=' AND a.status=?';$args[]=$status;}if($year){$sql.=' AND a.school_year_id=?';$args[]=$year;}
        $sql.=' GROUP BY a.id ORDER BY a.created_at DESC LIMIT 300';$stmt=$pdo->prepare($sql);$stmt->execute($args);
        $summary=$pdo->query('SELECT COALESCE(SUM(a.amount),0) assessed,COALESCE(SUM(x.paid),0) collected,COALESCE(SUM(CASE WHEN a.status="open" THEN a.amount-COALESCE(x.paid,0) ELSE 0 END),0) outstanding FROM tuition_assessments a LEFT JOIN (SELECT tuition_assessment_id,SUM(amount) paid FROM tuition_payments GROUP BY tuition_assessment_id) x ON x.tuition_assessment_id=a.id WHERE a.status NOT IN ("cancelled","waived")')->fetch();
        $schedules=$pdo->query('SELECT fs.*,g.name grade_level,sy.name school_year,t.name term_name FROM tuition_fee_schedules fs JOIN grade_levels g ON g.id=fs.grade_level_id JOIN school_years sy ON sy.id=fs.school_year_id LEFT JOIN terms t ON t.id=fs.term_id ORDER BY sy.starts_on DESC,g.sequence_no,fs.created_at DESC')->fetchAll();
        View::render('tuition/index',['assessments'=>$stmt->fetchAll(),'summary'=>$summary,'schedules'=>$schedules,'q'=>$q,'status'=>$status,'year'=>$year,'schoolYears'=>$pdo->query('SELECT * FROM school_years ORDER BY starts_on DESC')->fetchAll(),'currency'=>$this->currency()]);
    }

    public function create():void{View::render('tuition/form',$this->scheduleFormData([],[]));}

    public function store():void
    {
        $in=['grade_level_id'=>(int)($_POST['grade_level_id']??0),'school_year_id'=>(int)($_POST['school_year_id']??0),'term_id'=>(int)($_POST['term_id']??0),'description'=>trim($_POST['description']??''),'due_date'=>trim($_POST['due_date']??'')];
        [$in,$amount,$errors]=$this->readFees($in);if(!$in['grade_level_id'])$errors[]='Select a grade level.';if(!$in['school_year_id'])$errors[]='Select a school year.';if($amount<=0)$errors[]='Enter at least one fee amount greater than zero.';if($in['due_date']!==''&&!$this->validDate($in['due_date']))$errors[]='Due date is invalid.';
        $pdo=Database::connection();if(!$errors){$check=$pdo->prepare('SELECT COUNT(*) FROM grade_levels g JOIN school_years sy WHERE g.id=? AND sy.id=?');$check->execute([$in['grade_level_id'],$in['school_year_id']]);if(!(int)$check->fetchColumn())$errors[]='The selected grade level or school year is invalid.';if($in['term_id']){$term=$pdo->prepare('SELECT id FROM terms WHERE id=? AND school_year_id=?');$term->execute([$in['term_id'],$in['school_year_id']]);if(!$term->fetch())$errors[]='The selected term does not belong to the school year.';}}
        if($errors){View::render('tuition/form',$this->scheduleFormData(array_values(array_unique($errors)),$in));return;}
        if($in['description']==='')$in['description']='Grade-level school fees';
        $pdo->prepare('INSERT INTO tuition_fee_schedules(grade_level_id,school_year_id,term_id,description,tuition_fee_amount,entrance_fee_amount,paces_fee_amount,closing_fee_amount,shuttle_fee_amount,amount,due_date,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$in['grade_level_id'],$in['school_year_id'],$in['term_id']?:null,$in['description'],...array_map(fn($key)=>number_format((float)$in[$key],2,'.',''),self::FEE_KEYS),$in['amount'],$in['due_date']?:null,Auth::user()['id']]);
        $id=(int)$pdo->lastInsertId();Auth::audit('tuition.grade_assessment_created','tuition_fee_schedules',(string)$id,null,$in);flash('success','Grade-level fee assessment created. Students can now make payments against it.');Auth::redirect('/tuition');
    }

    public function paymentForm():void{View::render('tuition/payment',$this->paymentFormData([],[]));}

    public function makePayment():void
    {
        $in=['student_id'=>(int)($_POST['student_id']??0),'fee_schedule_id'=>(int)($_POST['fee_schedule_id']??0),'amount'=>trim($_POST['amount']??''),'payment_for'=>$_POST['payment_for']??'tuition','paid_on'=>trim($_POST['paid_on']??''),'receipt_no'=>trim($_POST['receipt_no']??''),'payment_method'=>$_POST['payment_method']??'cash','remarks'=>trim($_POST['remarks']??'')];$errors=[];
        if(!$in['student_id'])$errors[]='Select a student.';if(!$in['fee_schedule_id'])$errors[]='Select the applicable grade-level assessment.';if(!is_numeric($in['amount'])||(float)$in['amount']<=0)$errors[]='Payment amount must be greater than zero.';if(!$this->categoryColumn($in['payment_for'])&&$in['payment_for']!=='other')$errors[]='Select what this payment is for.';if(!$this->validDate($in['paid_on']))$errors[]='Payment date is invalid.';if(!in_array($in['payment_method'],['cash','bank_transfer','card','cheque','other'],true))$errors[]='Payment method is invalid.';
        if($errors){View::render('tuition/payment',$this->paymentFormData($errors,$in));return;}
        $pdo=Database::connection();$pdo->beginTransaction();
        try{
            $scheduleStmt=$pdo->prepare('SELECT * FROM tuition_fee_schedules WHERE id=? AND status="active" FOR UPDATE');$scheduleStmt->execute([$in['fee_schedule_id']]);$schedule=$scheduleStmt->fetch();if(!$schedule)throw new \RuntimeException('The selected assessment is no longer available.');
            $eligible=$pdo->prepare('SELECT e.id FROM enrollments e JOIN sections sec ON sec.id=e.section_id WHERE e.student_id=? AND e.school_year_id=? AND sec.grade_level_id=? AND e.status="enrolled"');$eligible->execute([$in['student_id'],$schedule['school_year_id'],$schedule['grade_level_id']]);if(!$eligible->fetch())throw new \RuntimeException('This student is not enrolled in the grade level and school year for that assessment.');
            $assessmentStmt=$pdo->prepare('SELECT * FROM tuition_assessments WHERE student_id=? AND fee_schedule_id=? FOR UPDATE');$assessmentStmt->execute([$in['student_id'],$in['fee_schedule_id']]);$assessment=$assessmentStmt->fetch();
            if(!$assessment){$pdo->prepare('INSERT INTO tuition_assessments(student_id,fee_schedule_id,school_year_id,term_id,description,tuition_fee_amount,entrance_fee_amount,paces_fee_amount,closing_fee_amount,shuttle_fee_amount,amount,due_date,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$in['student_id'],$schedule['id'],$schedule['school_year_id'],$schedule['term_id'],$schedule['description'],...array_map(fn($key)=>$schedule[$key],self::FEE_KEYS),$schedule['amount'],$schedule['due_date'],Auth::user()['id']]);$assessmentId=(int)$pdo->lastInsertId();$assessment=array_merge($schedule,['id'=>$assessmentId,'status'=>'open']);}else{$assessmentId=(int)$assessment['id'];}
            if(in_array($assessment['status'],['waived','cancelled'],true))throw new \RuntimeException('This student assessment cannot accept payments.');
            $sum=$pdo->prepare('SELECT COALESCE(SUM(amount),0) FROM tuition_payments WHERE tuition_assessment_id=?');$sum->execute([$assessmentId]);$balance=(float)$assessment['amount']-(float)$sum->fetchColumn();$amount=(float)$in['amount'];if($amount>$balance+0.001)throw new \RuntimeException('Payment exceeds the remaining balance of '.$this->currency().' '.number_format($balance,2).'.');
            $categoryColumn=$this->categoryColumn($in['payment_for']);if($categoryColumn){$categoryPaid=$pdo->prepare('SELECT COALESCE(SUM(amount),0) FROM tuition_payments WHERE tuition_assessment_id=? AND payment_for=?');$categoryPaid->execute([$assessmentId,$in['payment_for']]);$categoryBalance=(float)$assessment[$categoryColumn]-(float)$categoryPaid->fetchColumn();if($amount>$categoryBalance+0.001)throw new \RuntimeException('Payment exceeds the remaining '.str_replace('_',' ',$in['payment_for']).' amount of '.$this->currency().' '.number_format(max(0,$categoryBalance),2).'.');}
            $receipt=$in['receipt_no']!==''?substr($in['receipt_no'],0,60):'OR-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));
            $pdo->prepare('INSERT INTO tuition_payments(tuition_assessment_id,receipt_no,amount,payment_for,paid_on,payment_method,remarks,received_by) VALUES(?,?,?,?,?,?,?,?)')->execute([$assessmentId,$receipt,number_format($amount,2,'.',''),$in['payment_for'],$in['paid_on'],$in['payment_method'],substr($in['remarks'],0,500)?:null,Auth::user()['id']]);if(abs($balance-$amount)<0.01)$pdo->prepare('UPDATE tuition_assessments SET status="paid" WHERE id=?')->execute([$assessmentId]);
            $pdo->commit();Auth::audit('tuition.payment_recorded','tuition_assessments',(string)$assessmentId,null,['student_id'=>$in['student_id'],'schedule_id'=>$in['fee_schedule_id'],'amount'=>$amount]);flash('success','Student payment recorded.');Auth::redirect('/tuition/'.$assessmentId);
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$errors[]=$e instanceof \PDOException?'The receipt number is already in use.':$e->getMessage();View::render('tuition/payment',$this->paymentFormData($errors,$in));}
    }

    public function show(string $id):void{$assessment=$this->find((int)$id);if(!$assessment)return;$stmt=Database::connection()->prepare('SELECT p.*,u.display_name receiver FROM tuition_payments p JOIN users u ON u.id=p.received_by WHERE p.tuition_assessment_id=? ORDER BY p.paid_on DESC,p.id DESC');$stmt->execute([$id]);View::render('tuition/show',['assessment'=>$assessment,'payments'=>$stmt->fetchAll(),'currency'=>$this->currency()]);}

    public function receipt(string $id,string $paymentId):void
    {
        $pdo=Database::connection();$stmt=$pdo->prepare('SELECT p.*,u.display_name receiver,a.description,a.amount assessment_amount,s.student_no,CONCAT(s.first_name," ",s.last_name) student_name,sy.name school_year,t.name term_name,(a.amount-(SELECT COALESCE(SUM(px.amount),0) FROM tuition_payments px WHERE px.tuition_assessment_id=a.id)) account_balance FROM tuition_payments p JOIN tuition_assessments a ON a.id=p.tuition_assessment_id JOIN students s ON s.id=a.student_id JOIN school_years sy ON sy.id=a.school_year_id LEFT JOIN terms t ON t.id=a.term_id JOIN users u ON u.id=p.received_by WHERE a.id=? AND p.id=?');$stmt->execute([(int)$id,(int)$paymentId]);$payment=$stmt->fetch();
        if(!$payment){http_response_code(404);View::render('errors/message',['title'=>'Receipt not found','message'=>'The requested tuition payment receipt does not exist.']);return;}
        $settings=[];foreach($pdo->query('SELECT setting_key,setting_value FROM system_settings WHERE setting_key IN ("school_name","school_address","school_phone","school_email","school_logo")')->fetchAll() as $row)$settings[$row['setting_key']]=$row['setting_value'];
        View::render('tuition/receipt',['payment'=>$payment,'settings'=>$settings,'currency'=>$this->currency(),'title'=>'Receipt '.$payment['receipt_no']],'layouts/receipt');
    }

    public function recordPayment(string $id):void
    {
        $pdo=Database::connection();$amount=(float)($_POST['amount']??0);$paymentFor=$_POST['payment_for']??'tuition';$receipt=trim($_POST['receipt_no']??'');$paidOn=trim($_POST['paid_on']??'');$method=$_POST['payment_method']??'cash';if($amount<=0||(!$this->categoryColumn($paymentFor)&&$paymentFor!=='other')||!$this->validDate($paidOn)||!in_array($method,['cash','bank_transfer','card','cheque','other'],true)){flash('error','Enter a valid amount, payment category, date, and method.');Auth::redirect('/tuition/'.$id);}if($receipt==='')$receipt='OR-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));
        $pdo->beginTransaction();try{$lock=$pdo->prepare('SELECT * FROM tuition_assessments WHERE id=? FOR UPDATE');$lock->execute([(int)$id]);$assessment=$lock->fetch();if(!$assessment||in_array($assessment['status'],['waived','cancelled'],true))throw new \RuntimeException('This assessment cannot accept payments.');$sum=$pdo->prepare('SELECT COALESCE(SUM(amount),0) FROM tuition_payments WHERE tuition_assessment_id=?');$sum->execute([(int)$id]);$balance=(float)$assessment['amount']-(float)$sum->fetchColumn();if($amount>$balance+0.001)throw new \RuntimeException('Payment exceeds the remaining balance.');$categoryColumn=$this->categoryColumn($paymentFor);if($categoryColumn){$categoryPaid=$pdo->prepare('SELECT COALESCE(SUM(amount),0) FROM tuition_payments WHERE tuition_assessment_id=? AND payment_for=?');$categoryPaid->execute([(int)$id,$paymentFor]);$categoryBalance=(float)$assessment[$categoryColumn]-(float)$categoryPaid->fetchColumn();if($amount>$categoryBalance+0.001)throw new \RuntimeException('Payment exceeds the remaining '.str_replace('_',' ',$paymentFor).' amount.');}$pdo->prepare('INSERT INTO tuition_payments(tuition_assessment_id,receipt_no,amount,payment_for,paid_on,payment_method,remarks,received_by) VALUES(?,?,?,?,?,?,?,?)')->execute([(int)$id,substr($receipt,0,60),number_format($amount,2,'.',''),$paymentFor,$paidOn,$method,substr(trim($_POST['remarks']??''),0,500)?:null,Auth::user()['id']]);if(abs($balance-$amount)<0.01)$pdo->prepare('UPDATE tuition_assessments SET status="paid" WHERE id=?')->execute([(int)$id]);$pdo->commit();flash('success','Tuition payment recorded.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e instanceof \PDOException?'Receipt number is already in use.':$e->getMessage());}Auth::redirect('/tuition/'.$id);
    }

    public function updateStatus(string $id):void{$assessment=$this->find((int)$id);if(!$assessment)return;$status=$_POST['status']??'';if(!in_array($status,['open','waived','cancelled'],true)){flash('error','Invalid assessment status.');Auth::redirect('/tuition/'.$id);}if((float)$assessment['paid_amount']>0&&$status!=='open'){flash('error','An assessment with payments cannot be waived or cancelled.');Auth::redirect('/tuition/'.$id);}Database::connection()->prepare('UPDATE tuition_assessments SET status=? WHERE id=?')->execute([$status,(int)$id]);flash('success','Assessment status updated.');Auth::redirect('/tuition/'.$id);}

    private function scheduleFormData(array $errors,array $input):array{$pdo=Database::connection();return['grades'=>$pdo->query('SELECT * FROM grade_levels WHERE status="active" ORDER BY sequence_no')->fetchAll(),'schoolYears'=>$pdo->query('SELECT * FROM school_years ORDER BY starts_on DESC')->fetchAll(),'terms'=>$pdo->query('SELECT t.*,sy.name school_year FROM terms t JOIN school_years sy ON sy.id=t.school_year_id ORDER BY sy.starts_on DESC,t.sequence_no')->fetchAll(),'errors'=>$errors,'input'=>$input,'currency'=>$this->currency()];}
    private function paymentFormData(array $errors,array $input):array{$pdo=Database::connection();$students=$pdo->query('SELECT st.id,st.student_no,st.first_name,st.last_name,e.school_year_id,sec.grade_level_id,g.name grade_level,sy.name school_year FROM students st JOIN enrollments e ON e.student_id=st.id AND e.status="enrolled" JOIN sections sec ON sec.id=e.section_id JOIN grade_levels g ON g.id=sec.grade_level_id JOIN school_years sy ON sy.id=e.school_year_id WHERE st.student_status="active" ORDER BY sy.starts_on DESC,st.last_name,st.first_name')->fetchAll();$seen=[];$students=array_values(array_filter($students,function($row)use(&$seen){if(isset($seen[$row['id']]))return false;$seen[$row['id']]=true;return true;}));$schedules=$pdo->query('SELECT fs.*,g.name grade_level,sy.name school_year,t.name term_name FROM tuition_fee_schedules fs JOIN grade_levels g ON g.id=fs.grade_level_id JOIN school_years sy ON sy.id=fs.school_year_id LEFT JOIN terms t ON t.id=fs.term_id WHERE fs.status="active" ORDER BY sy.starts_on DESC,g.sequence_no,fs.created_at DESC')->fetchAll();return compact('students','schedules','errors','input')+['currency'=>$this->currency()];}
    private function readFees(array $in):array{$errors=[];$amount=0.0;foreach(self::FEE_KEYS as $key){$raw=trim((string)($_POST[$key]??''));$in[$key]=$raw===''?'0':$raw;if(!is_numeric($in[$key])||(float)$in[$key]<0){$errors[]='Fee amounts must be valid numbers of zero or more.';continue;}$amount+=(float)$in[$key];}$in['amount']=number_format($amount,2,'.','');return[$in,$amount,$errors];}
    private function categoryColumn(string $category):?string{return['tuition'=>'tuition_fee_amount','entrance_fee'=>'entrance_fee_amount','paces'=>'paces_fee_amount','closing_fee'=>'closing_fee_amount','shuttle'=>'shuttle_fee_amount'][$category]??null;}
    private function find(int $id):?array{$stmt=Database::connection()->prepare('SELECT a.*,s.student_no,CONCAT(s.first_name," ",s.last_name) student_name,sy.name school_year,t.name term_name,COALESCE(SUM(p.amount),0) paid_amount,(a.amount-COALESCE(SUM(p.amount),0)) balance FROM tuition_assessments a JOIN students s ON s.id=a.student_id JOIN school_years sy ON sy.id=a.school_year_id LEFT JOIN terms t ON t.id=a.term_id LEFT JOIN tuition_payments p ON p.tuition_assessment_id=a.id WHERE a.id=? GROUP BY a.id');$stmt->execute([$id]);$row=$stmt->fetch();if(!$row){http_response_code(404);View::render('errors/message',['title'=>'Assessment not found','message'=>'The requested tuition assessment does not exist.']);return null;}return$row;}
    private function currency():string{$value=Database::connection()->query('SELECT setting_value FROM system_settings WHERE setting_key="currency_symbol"')->fetchColumn();return$value?:'PHP';}
    private function validDate(string $date):bool{$d=DateTimeImmutable::createFromFormat('Y-m-d',$date);return$d&&$d->format('Y-m-d')===$date;}
}
