<?php
use App\Core\Auth;
use App\Core\Authorization;
use App\Core\Csrf;
use App\Core\Database;
use App\Core\Env;
$requestPath='/' . trim((string)parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH),'/');
$applicationBase=rtrim((string)parse_url(Env::get('APP_URL',''),PHP_URL_PATH),'/');
if($applicationBase!==''&&str_starts_with($requestPath,$applicationBase)){$requestPath=substr($requestPath,strlen($applicationBase))?:'/';}
$active=static fn(string $needle):string=>preg_match('#^'.preg_quote($needle,'#').'(?:/|$)#',$requestPath)?' active':'';
$branding=[];
$logoStatement=Database::connection()->query('SELECT setting_key,setting_value FROM system_settings WHERE setting_key IN ("school_logo","school_logo_position_y","school_name")');
foreach($logoStatement->fetchAll() as $setting){$branding[$setting['setting_key']]=$setting['setting_value'];}
$schoolLogo=$branding['school_logo']??null;
$schoolLogoPositionY=max(0,min(100,(int)($branding['school_logo_position_y']??50)));
$schoolName=trim((string)($branding['school_name']??''))?:'School Management';
$studentNavId=Auth::check()&&Authorization::isStudentOnly()?Authorization::ownStudentId():null;
$studentNavHref=$studentNavId!==null?'/students/'.$studentNavId:'/students';
$studentNavLabel=Auth::check()&&Authorization::isStudentOnly()?'My profile':(Auth::check()&&Authorization::isTeacherOnly()?'My assigned students':'Students');
$teacherNavId=Auth::check()&&Authorization::isTeacherOnly()?Authorization::ownTeacherId():null;
$teacherNavHref=$teacherNavId!==null?'/teachers/'.$teacherNavId:'/teachers';
$teacherNavLabel=Auth::check()&&Authorization::isTeacherOnly()?'My profile':'Teachers';
$styles=['app.css','modules.css'];
if(str_starts_with($requestPath,'/attendance')) $styles[]='attendance.css';
if(str_starts_with($requestPath,'/events')) $styles[]='events.css';
if(str_starts_with($requestPath,'/reports')) $styles[]='reports.css';
if(str_starts_with($requestPath,'/admin/settings')||str_starts_with($requestPath,'/admin/audit')||str_starts_with($requestPath,'/admin/backups')||str_starts_with($requestPath,'/dashboard')) $styles[]='operations.css';
$styles[]='navigation.css';
$styles[]='theme-purple.css';
if(str_starts_with($requestPath,'/dashboard')){$styles[]='dashboard-purple.css';$styles[]='birthdays.css';}
$styles[]='branding.css?v=4';
$styles[]='layout-fixes.css';
if(str_starts_with($requestPath,'/tuition')){$styles[]='tuition.css?v=2';$styles[]='tuition-compact.css?v=1';$styles[]='tuition-form.css?v=1';}
if(str_starts_with($requestPath,'/insurance')){$styles[]='insurance.css';$styles[]='insurance-fixes.css';}
if(str_starts_with($requestPath,'/uniform-id')||str_starts_with($requestPath,'/students')||str_starts_with($requestPath,'/teachers')) $styles[]='inventory.css?v=4';
if(str_starts_with($requestPath,'/students')) $styles[]='students.css?v=2';
if(str_starts_with($requestPath,'/teachers')) $styles[]='teachers.css?v=1';
if(str_contains($requestPath,'/import')) $styles[]='imports.css';
$styles[]='sidebar-modern.css?v=2';
$styles[]='ui-polish.css?v=3';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?=e($title??'School Monitoring System')?></title>
<?php foreach($styles as $style):?><link rel="stylesheet" href="<?=e(url('/assets/css/'.$style))?>"><?php endforeach;?></head>
<body class="app-body"><a class="skip-link" href="#main-content">Skip to main content</a><div class="app-shell"><aside class="sidebar" id="app-sidebar"><a class="sidebar-brand<?=$schoolLogo?' has-logo':''?>" href="<?=e(url('/dashboard'))?>"><?php if($schoolLogo):?><span class="sidebar-logo-frame" data-sidebar-logo-frame style="background-image:url('<?=e(url('/'.$schoolLogo))?>');background-position:center <?=$schoolLogoPositionY?>%"><img src="<?=e(url('/'.$schoolLogo))?>" alt="<?=e($schoolName)?> logo"></span><?php else:?><span class="brand-orb">SM</span><?php endif;?><span class="brand-title"><strong><?=e($schoolName)?></strong><small>School operations ledger</small></span></a>
<?php if(Auth::check()):?><nav class="sidebar-nav" aria-label="Main navigation"><p class="nav-label">Workspace</p>
<?php if(Authorization::allows('dashboard.view')):?><a class="<?=$active('/dashboard')?>" href="<?=e(url('/dashboard'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg></span>Dashboard</a><?php endif;?>
<?php if(Authorization::allows('students.view')):?><a class="<?=$active('/students')?>" href="<?=e(url($studentNavHref))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m2 10 10-5 10 5-10 5Z"/><path d="M6 12v5c3 2 9 2 12 0v-5M22 10v6"/></svg></span><?=e($studentNavLabel)?></a><?php endif;?>
<?php if(Authorization::allows('teachers.view')):?><a class="<?=$active('/teachers')?>" href="<?=e(url($teacherNavHref))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M3 4h18v12H3zM8 20l4-4 4 4"/><circle cx="8" cy="9" r="2"/><path d="M12 8h5M12 12h5"/></svg></span><?=e($teacherNavLabel)?></a><?php endif;?>
<?php if(Authorization::allows('attendance.view')):?><a class="<?=$active('/attendance')?>" href="<?=e(url('/attendance/students'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="M9 3v3M15 3v3M8 11l2 2 5-5M8 17h8"/></svg></span>Attendance</a><?php endif;?>
<?php if(Authorization::allows('events.view')):?><a class="<?=$active('/events')?>" href="<?=e(url('/events'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18M8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01"/></svg></span>Events</a><?php endif;?>
<?php if(Authorization::allows('reports.view')):?><a class="<?=$active('/reports')?>" href="<?=e(url('/reports'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg></span>Reports</a><?php endif;?>
<?php if(Authorization::allows('tuition.view')):?><a class="<?=$active('/tuition')?>" href="<?=e(url('/tuition'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><rect x="3" y="6" width="18" height="14" rx="2"/><path d="M16 13h5M3 10h18M7 6V4h10v2"/></svg></span>Tuition fees</a><?php endif;?>
<?php if(Authorization::allows('insurance.view')):?><a class="<?=$active('/insurance')?>" href="<?=e(url('/insurance'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-5"/></svg></span>Insurance</a><?php endif;?>
<?php if(Authorization::allows('inventory.view')):?><a class="<?=$active('/uniform-id')?>" href="<?=e(url('/uniform-id'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m21 8-9 5-9-5 9-5 9 5Z"/><path d="m3 8 9 5v9l-9-5ZM21 8l-9 5v9l9-5Z"/></svg></span>Uniform &amp; IDs</a><?php endif;?>
<p class="nav-label">Administration</p>
<?php if(Authorization::allows('academics.view')):?><a class="<?=$active('/admin/academics')?>" href="<?=e(url('/admin/academics'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 4h6a3 3 0 0 1 3 3v13a3 3 0 0 0-3-3H4ZM20 4h-6a3 3 0 0 0-3 3v13a3 3 0 0 1 3-3h6Z"/></svg></span>Academics</a><?php endif;?>
<?php if(Authorization::allows('users.view')):?><a class="<?=$active('/admin/users')?>" href="<?=e(url('/admin/users'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg></span>Users</a><?php endif;?>
<?php if(Authorization::allows('roles.view')):?><a class="<?=$active('/admin/roles')?>" href="<?=e(url('/admin/roles'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="8" cy="15" r="4"/><path d="m11 12 8-8M17 4l3 3M15 6l3 3"/></svg></span>Permissions</a><?php endif;?>
<?php if(Authorization::allows('settings.view')):?><a class="<?=$active('/admin/settings')?>" href="<?=e(url('/admin/settings'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1A7 7 0 0 0 15 6l-.3-2.6h-4L10.4 6A7 7 0 0 0 9 7L6.5 6l-2 3.4L6.6 11a7 7 0 0 0 0 2L4.5 14.5l2 3.4 2.4-1A7 7 0 0 0 10.4 18l.3 2.6h4L15 18a7 7 0 0 0 1.5-1l2.4 1 2-3.4L18.9 13c.1-.3.1-.7.1-1Z"/></svg></span>Settings</a><?php endif;?>
<?php if(Authorization::allows('audit.view')):?><a class="<?=$active('/admin/audit')?>" href="<?=e(url('/admin/audit'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M3 12a9 9 0 1 0 3-6.7L3 8M3 3v5h5M12 7v5l3 2"/></svg></span>Audit log</a><?php endif;?>
<?php if(Authorization::allows('backups.view')):?><a class="<?=$active('/admin/backups')?>" href="<?=e(url('/admin/backups'))?>"><span class="nav-mark"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 11v6c0 1.7 3.6 3 8 3 1.2 0 2.3-.1 3.3-.3M18 16l3 3-3 3M21 19h-5"/></svg></span>Backups</a><?php endif;?></nav>
<div class="sidebar-user"><span class="user-avatar"><?=e(strtoupper(substr(Auth::user()['display_name'],0,1)))?></span><span class="user-copy"><strong><?=e(Auth::user()['display_name'])?></strong><small><?=e(Auth::user()['username'])?></small></span><form method="post" action="<?=e(url('/logout'))?>"><?=Csrf::field()?><button class="logout-button" title="Sign out" aria-label="Sign out"><svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m10 17 5-5-5-5M15 12H3M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/></svg></button></form></div><?php endif;?></aside>
<section class="main-area"><header class="mobile-topbar"><button type="button" class="menu-button" data-menu-toggle aria-label="Open navigation" aria-controls="app-sidebar" aria-expanded="false"><span class="mobile-menu-icon" aria-hidden="true"><span></span></span></button><strong><?=e($schoolName)?></strong><span class="mobile-avatar" aria-hidden="true"><?=Auth::check()?e(strtoupper(substr(Auth::user()['display_name'],0,1))):'SM'?></span></header><main class="content-wrap" id="main-content" tabindex="-1"><?php if($rawCredentials=flash('account_credentials')):?><?php $credentials=json_decode($rawCredentials,true)?:[];?><div class="alert success account-credentials" role="status"><strong><?=e($credentials['notice']??'Login account created')?></strong><br>Username: <code><?=e($credentials['username']??'')?></code><br>Temporary password: <code><?=e($credentials['temporary_password']??'')?></code><br><small>Give these credentials to the account owner securely. This temporary password is shown only once and must be changed at first login.</small></div><?php endif;?><?php if($message=flash('success')):?><div class="alert success" role="status"><?=e($message)?></div><?php endif;?><?php if($message=flash('error')):?><div class="alert danger" role="alert"><?=e($message)?></div><?php endif;?><?=$content?></main></section></div><div class="sidebar-scrim" data-menu-toggle aria-hidden="true"></div><script>
(()=>{const body=document.body,toggles=[...document.querySelectorAll('[data-menu-toggle]')],menuButton=document.querySelector('.menu-button'),sidebar=document.getElementById('app-sidebar');const setMenu=open=>{body.classList.toggle('menu-open',open);menuButton?.setAttribute('aria-expanded',String(open));menuButton?.setAttribute('aria-label',open?'Close navigation':'Open navigation');if(open)sidebar?.querySelector('a')?.focus();else if(document.activeElement&&sidebar?.contains(document.activeElement))menuButton?.focus();};toggles.forEach(button=>button.addEventListener('click',()=>setMenu(!body.classList.contains('menu-open'))));sidebar?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{if(matchMedia('(max-width: 800px)').matches)setMenu(false)}));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&body.classList.contains('menu-open'))setMenu(false)});
const statusGroups={success:['active','paid','present','published','completed','returned','approved','enabled','primary','system'],warning:['pending','draft','ongoing','open','under review','submitted','on leave','expiring soon'],danger:['inactive','expired','cancelled','withdrawn','separated','rejected','locked','absent','overdue'],info:['teacher','student','staff','invited','late','excused','graduated','transferred'],neutral:['unrecorded','waived']};document.querySelectorAll('.badge').forEach(badge=>{const value=badge.textContent.trim().toLowerCase().replaceAll('_',' ');for(const [group,values] of Object.entries(statusGroups)){if(values.includes(value)){badge.classList.add('status-'+group);break;}}});document.querySelectorAll('.alert.danger').forEach(alert=>alert.setAttribute('role','alert'));document.querySelectorAll('thead th:last-child:empty').forEach(th=>{th.textContent='Actions';th.classList.add('action-column')});})();
</script></body></html>
